#!/usr/bin/env php
<?php
namespace think;

// 命令行入口文件
// 加载基础文件
require __DIR__ . '/vendor/autoload.php';

// 判断当前环境
$env = empty(get_cfg_var('env'))?'local':get_cfg_var('env');

// 应用初始化
(new App())->setEnvName($env)->console->run();